---
output: 
  html_document:
    css: PrevVisit_modules/www/styles_prevvisit.css
    anchor_sections: FALSE
params:
  yearpv: 2022
  year_curr: 2025
  parkcode: "MABI"
  panel: 3
  print: FALSE
---
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '')

# Hierarchy of plot viewer report: 
#--- PrevVisit_Plot_Viewer_NETN_All.Rmd generates the Summary tab and iterates through the park's list of plots.
#------ PrevVisit_modules/PrevVisit_Plot_Viewer_NETN_Indiv.Rmd renders each plot's report within the plot-named tabs. 
#       This report shows the order of the modules that are rendered and allows you to turn them off, if they're failing.
#---------- PrevVisit_modules/PrevVisit_1A_Stand_Data_wide.Rmd (and others with numbers) are individual data modules. 
#           If you try to knit the plot viewer and it fails, the error should tell you which module failed. 
#           Where NETN and MIDN can use the same module, only 1 file exists. Where there are separate modules, 
#           MIDN's module is named. 
#---------- !!!! NOTE: The photopoints, which are rendered last, must either be updated to where the photos for a given year
#           are located on the Z drive, your laptop, or an external drive. The file that needs to be updated/checked is
#           PrevVisit_modules/PrevVisit_5A_Photopoints_wide.Rmd !!!!
```

# Previous visit data for `r paste0(params$parkcode, " ", params$yearpv)` {.tabset .tabset-pills}
```{r echo = F, include = F}
library(forestNETN)
library(pagedown)
library(tidyverse)
library(htmltools)
library(knitr)
#devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0") # for collapse_rows()
library(kableExtra)
library(ggrepel)
library(cowplot)
library(stringr)
library(DT) # for sort/filter table features
library(htmlwidgets)
# park = "ROVA"; year = as.numeric(2019); panel = 2
# params <- data.frame(yearpv = 2019, year_curr = 2024, parkcode = "ROVA", panel = 2, print = FALSE)
# importData()
# source("./PrevVisit_Modules/PrevVisit_FieldForms_NETN_compile.R")
soil_sch <- readxl::read_xlsx("./PrevVisit_Modules/12-year_Soil_Sample_Schedule.xlsx", sheet = params$parkcode)[,1:5]
colnames(soil_sch) <- c("park", "plot", "grts", "year", "post_covid_year")
```

```{r echo = F, include = F, cache = F}
# Create environment for rmds to pull params from
child_env <- new.env()
importData()

for(n in ls(VIEWS_NETN, all.names = TRUE)) assign(n, get(n, VIEWS_NETN), child_env)

year = as.numeric(params$yearpv)
park = params$parkcode
panel = params$panel

child_env$year <- year
child_env$park <- park
child_env$panel <- panel
child_env$print <- FALSE

child_env$plots <- joinLocEvent(park = park, 
                                from = year, 
                                  to = year, 
                                panel = panel,
                                locType = 'all') |> 
                        select(Plot_Name, SampleYear) |> 
                        arrange(Plot_Name)

child_env$plot_list <- child_env$plots$Plot_Name#[c(1:2)]
child_env$plot_name <- child_env$plot_list[1]

sys.source("./PrevVisit_modules/PrevVisit_FieldForms_NETN_compile.R", envir = child_env)
```


```{r echo = F, include = F}
# Summary Table for first tab
plot_info <- joinLocEvent(park = park, from = year, to = year, output = 'verbose', panel = panel, locType = 'all') |> 
             mutate(Unit = case_when(ParkSubUnit %in% "ACAD_MDI_East" ~ "East",
                                     ParkSubUnit %in% "ACAD_MDI_West" ~ "West",
                                     ParkSubUnit %in% "ACAD_Schoodic" ~ "Schoodic",
                                     ParkSubUnit %in% "ACAD_Isle_au_Haut" ~ "IAH", 
                                     TRUE ~ substr(ParkSubUnit, 6, nchar(ParkSubUnit)))) |> 
               select(Plot_Name, PlotCode, Unit, #Notes = PlotNotes, 
                      Directions)#, Stunted = IsStuntedWoodland)  

stand_info <- joinStandData(park = park, from = year, to = year, panel = panel, locType = 'all') |> 
  mutate(tree_cores = ifelse(ParkUnit == "MIMA", "Tree Cores", NA_character_)) |> 
  mutate(slope = case_when(PlotSlope >= 35 ~ "EXTREMELY STEEP",
                           between(PlotSlope, 35, 25) ~ "VERY STEEP",
                           between(PlotSlope, 25, 15) ~ "STEEP",
                           PlotSlope < 15 ~ NA_character_,
                           TRUE ~ NA_character_),
         crown = case_when(Pct_Crown_Closure == 5 ~ "VERY OPEN",
                           between(Pct_Crown_Closure, 17.5, 37.5) ~ "OPEN",
                           TRUE ~ NA_character_),
         rocky = case_when(between(Pct_Rock, 3, 36) ~ "Rocky",
                           Pct_Rock >= 37.5 ~ "Very Rocky"),
         stunt = ifelse(IsStuntedWoodland == TRUE, "Stunted Woodland", NA_character_),
         midstory = case_when(Txt_Understory_Mid == "95-100%" ~ "VERY DENSE MID-STORY",
                              Txt_Understory_Mid == '75-95%' ~ "Very dense mid-story",
                              Txt_Understory_Mid == '50-75%' ~ 'Dense mid-story',
                              TRUE ~ NA_character_),
         understory = case_when(Txt_Understory_Low == "0%" ~ "Bare understory",
                                Txt_Understory_Low %in% c("1-5%", "5-25%") ~ 
                                  "Sparse understory"), 
         water = ifelse(!Water_on_Plot %in% "None", Water_on_Plot, NA_character_),
         water_cov = paste0("Water cover: ", Txt_Water)) |> 
  select(Plot_Name, slope, crown, rocky, stunt, midstory, understory, water, 
         water_cov, tree_cores) |> 
  pivot_longer(-Plot_Name, names_to = "Metric", values_to = "Value") |> 
  filter(!is.na(Value)) |> filter(!Value %in% "Water cover: 0%")

stand_conc <- stand_info |> group_by(Plot_Name) |> summarize(Concerns = toString(unique(Value)))

visit_notes <- joinVisitNotes(park = park, from = year, to = year, noteType = "all", panel = panel, locType = 'all') |> 
  filter(Note_Type %in% c("Plot_Notes", "Stand_Notes", "Stand_Disturbances")) |> 
  mutate(Notes = ifelse(Note_Type == "Stand_Disturbances", paste0("Disturbance: ", Notes), Notes),
         order = case_when(Note_Type == "Plot_Notes" ~ 1,
                           Note_Type == "Stand_Notes" ~ 2,
                           TRUE ~ 3)) |> arrange(Plot_Name, order) |> 
  select(Plot_Name, Notes) |> group_by(Plot_Name) |> summarize(Notes = toString(unique(Notes)))

trees <- joinTreeData(park = park, from = year, to = year, status = 'active', panel = panel, locType = 'all') |> 
  filter(!TreeStatusCode %in% "DF") |> 
  group_by(Plot_Name) |> summarize(num_trees = sum(num_stems))

regen <- joinRegenData(park = park, from = year, to = year, panel = panel, locType = 'all') |> 
  group_by(Plot_Name) |> summarize(num_saps = round(sum(sap_den) * 3, 1),
                                   num_seeds = round(sum(seed_den) * 3, 1))

shrubs <- joinMicroShrubData(park = park, from = year, to = year, panel = panel, locType = 'all') |> 
  select(Plot_Name, shrub_avg_cov) |> 
  group_by(Plot_Name) |> summarize(shrub_avg_cov = sum(shrub_avg_cov, na.rm = T)) |> 
  mutate(Concerns = case_when(shrub_avg_cov >= 70 ~ "VERY DENSE SHRUBS",
                             between(shrub_avg_cov, 45, 70) ~ "DENSE SHRUBS",
                             between(shrub_avg_cov, 25, 25) ~ "SHRUBS",
                             TRUE ~ NA_character_)) |> 
  select(Plot_Name, Concerns) |> filter(!is.na(Concerns))


quadspp <- joinQuadSpecies(park = park, from = year, to = year, panel = panel, locType = 'all') |> 
  filter(IsGerminant == FALSE) |> 
  group_by(Plot_Name) |> 
  summarize(num_quadspp = sum(!ScientificName %in% "None present"))

addspp <- joinAdditionalSpecies(park = park, from = year, to = year, panel = panel, locType = 'all') |> 
  group_by(Plot_Name) |> summarize(num_addspp = sum(addspp_present))

soil_sch1 <- soil_sch |> 
  mutate(Plot_Name = paste0(park, "-", str_pad(plot, 3, pad = "0")),
         Concerns = "SOIL SAMPLE") |>
  filter(park == park) |> filter(post_covid_year == params$year_curr) |> 
  select(Plot_Name, Concerns)

cwd_conc <- VIEWS_NETN$CWD_NETN |> filter(ParkUnit == park) |> filter(SampleYear == year) |> 
  filter(PanelCode == panel) |> 
  group_by(Plot_Name, SampleYear) |> summarize(num_cwd = sum(!is.na(Distance)), .groups = 'drop') |>
  mutate(Concerns = case_when(num_cwd > 25 ~ "TONS OF CWD",
                             between(num_cwd, 15, 25) ~ "Lots of CWD",
                             between(num_cwd, 8, 15) ~ "CWD",
                             TRUE ~ NA_character_)) |> 
  filter(!is.na(Concerns)) |> select(Plot_Name, Concerns)


concerns <- rbind(stand_conc, shrubs, soil_sch1, cwd_conc) |> 
  group_by(Plot_Name) |> summarize(Concerns = toString(unique(Concerns)))

comb <- purrr::reduce(list(plot_info, visit_notes, trees, regen, 
                           quadspp, addspp, concerns), 
                      left_join, by = "Plot_Name") |> 
  select(PlotCode, Unit, #Stunt, 
         num_trees, num_saps, num_seeds, num_quadspp, num_addspp, 
         Notes, Directions, Concerns)


# Couldn't get dt to recognize the column widths, so hacked it with colnames. 
comb_tbl <- datatable(comb, class = 'cell-border stripe', rownames = FALSE,
                      width = '1200px',
                      extensions = c("FixedColumns", "Buttons"),
                      colnames = c("Plot", "Unit", #"Stunt", 
                                   "Trees", "Saps", "Seeds",
                                   "QuadSpp", "AddSpp", #"Notes", "Directions", "Concerns"),
                                   "Notes________________________", "Directions_______________________",
                                   "Concerns__________________"),
                      options = list(       
                        initComplete = htmlwidgets::JS(
                          "function(settings, json) {",
                            "$('body').css({'font-size': '11px'});",
                            "$('body').css({'font-family': 'Arial'});",
                            "$(this.api().table().header()).css({'font-size': '11px'});",
                            "$(this.api().table().header()).css({'font-family': 'Arial'});",
                          "}"),
                          #paste0("$(this.api().table().container()).css({'font-size': 12px;})}")),
                            
                                     pageLength = 10,
                                     autoWidth = FALSE, scrollX = TRUE,
                                     scrollY = '600px',
                                     scrollCollapse = TRUE,
                                     lengthMenu = c(5, 10, nrow(comb)),
                                     fixedColumns = list(leftColumns = 1),
                                     dom = "Blfrtip", buttons = c('copy', 'csv', 'print'),
                                     columnDefs = list(
                                       list(className = 'dt-center', targets = 0:5),
                                       list(className = 'dt-left', targets = 6:8)
                                       )),
                      filter = list(position = c('top'), clear = FALSE)#,
                      #editable = list(target = 'cell', disable = list(columns = 0:7))
                      ) 

```

## Summary {.tabset}
```{r echo = F, message = F, warning = F}
suppressWarnings(comb_tbl)
```

```{r results = 'asis', echo = F, eval = T}
res <- lapply(seq_along(child_env$plot_list), function(x) {
  
  child_env$plot_name = child_env$plot_list[[x]]

  knitr::knit_child(
    './PrevVisit_modules/PrevVisit_Plot_Viewer_NETN_Indiv.Rmd', 
     envir = child_env,
     quiet = TRUE )
  
})
cat(unlist(res), sep = '\n')
```

```{r}
rm(list = ls())
```

