---
output: 
  pagedown::html_paged:
    toc: false
    numbered_sections: false
---

### Previous Visit: Tree Conditions and Foliage for `r paste0(params$plot, '-', params$year)` {.page-break-before} 

<hr>


#### Tree Conditions

```{r treec, include = F}
treec_p <- treecondl |> filter(Plot_Name %in% params$plot) 
#treec_p <- treecondl |> filter(Plot_Name %in% "ACAD-029") 

treec_p_w <- treec_p |> select(Tag, Species = ScientificName, Status, 
                               Tot_Num = num_cond, Condition) |> 
  mutate(present = "X") |> 
  pivot_wider(names_from = Condition, values_from = present)

if(nrow(treec_p_w) > 0){
treec_tab <- kable(treec_p_w,
                  table.attr = "class='table-striped'",
                  format = 'html', align = c('c', 'l', rep('c', ncol(treec_p_w) - 2) )) |> 
             kable_styling(fixed_thead = TRUE, position = 'left', full_width = TRUE, 
                           font_size = 10) 
}
print_c <- ifelse(nrow(treec_p) > 0, TRUE, FALSE)
```

```{r treec_tab, eval = print_c}
treec_tab
```

```{r treec_cat, eval = !print_c, retults = 'asis'}
cat("No tree conditions were reported during this visit.")

```
