---
output: 
  html_document:
    css: www/styles_prevvisit.css
    anchor_sections: FALSE
params:
  print: FALSE
  parkcode: "APCO"
  yearpv: 2018
  plot_name: "APCO-262"
  
---
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '')

library(forestMIDN)
library(pagedown)
library(tidyverse)
library(htmltools)
library(knitr)
#devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0") # for collapse_rows()
library(kableExtra)
library(ggrepel)
library(cowplot)

#Comment out when done.
# year = as.numeric(params$yearpv)
# park = params$parkcode
# plot_name = params$plot_name

#importData()
#source("PrevVisit_FieldForms_MIDN_compile.R")
#sys.source("PrevVisit_FieldForms_NETN_compile.R", envir = child_env)
```

## `r paste0(plot_name)` {.tabset} 

### Plot & Visit Notes
```{r child = "PrevVisit_1B_Visit_Notes.Rmd"}
```

### Plot & Stand Data {.tabset}

#### Stand Data

```{r child = "PrevVisit_1A_Stand_Data_MIDN.Rmd"}
```

#### Disturbances
```{r child = 'PrevVisit_1A_Stand_Disturbances.Rmd'}
```

### Microplot 

```{r child = "PrevVisit_2A_Microplot_Sapling_Data_MIDN.Rmd"}
```


```{r child = "PrevVisit_2A_Microplot_Shrub_Data_MIDN.Rmd"}
```


### CWD 
```{r child = "PrevVisit_2B_CWD_Data.Rmd"}
```

### Trees {.tabset}

#### Tree Data  

```{r child = "PrevVisit_3A_Tree_Measurements.Rmd"}
```

```{r child = "PrevVisit_3B_Tree_Conditions.Rmd"}
```

<br>

```{r child = "PrevVisit_3C_Tree_Foliage_Cond.Rmd"}
```

### Quadrat Data {.tabset}

#### Quadrat Species
```{r child = "PrevVisit_4A_Quadrat_Data_MIDN.Rmd"}
```

#### Quadrat Seedlings
```{r child = "PrevVisit_4A_Quadrat_Seedlings_MIDN.Rmd"}
```


### Photopoints 

```{r child = "PrevVisit_5A_Photopoints_MIDN.Rmd"}
```

