---
output: 
  html_document:
    css: www/styles_prevvisit.css
    anchor_sections: FALSE
params:
  year: 2019
  park: "ACAD"
  plot_name: "ACAD-040"
  print: FALSE
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

library(pagedown)
library(tidyverse)
library(forestNETN)
library(htmltools)
library(knitr)
library(kableExtra)
library(ggrepel)
library(cowplot)
#devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0") # for collapse_rows()
library(kableExtra)
```

```{r import, include = FALSE, cache = FALSE}
forestNETN::importData()
```

```{r params, include = FALSE}
#params <- data.frame(year = 2019, plot_name = "ACAD-040")

year <- as.numeric(params$year)
park <- substr(params$plot_name, 1, 4)
plot_name <- params$plot_name
```

```{r source, include = FALSE}
source("PrevVisit_FieldForms_NETN_compile.R")
```
## `r paste0(plot_name, '-', year)` {.tabset .tabset-pills} 

### Plot & Visit Notes
```{r visit_notes, child = "PrevVisit_1B_Visit_Notes.Rmd"}
```

### Plot & Stand Data

```{r stand, child = "PrevVisit_1A_Stand_Data_wide.Rmd"}
```

### Microplot 

```{r micro2A, child = "PrevVisit_2A_Microplot_Data.Rmd"}
```

### CWD 
```{r cwd, child = "PrevVisit_2B_CWD_Data.Rmd"}
```

### Trees {.tabset}

#### Tree Data  

```{r tree3A, child = "PrevVisit_3A_Tree_Measurements.Rmd"}
```

```{r tree3B, child = "PrevVisit_3B_Tree_Conditions.Rmd"}
```

<br>

```{r tree3C, child = "PrevVisit_3C_Tree_Foliage_Cond.Rmd"}
```

### Quadrat Data 

<hr>

```{r quad1a, child = "PrevVisit_4A_Quadrat_Data.Rmd"}
```

### Photopoints 

<hr>

```{r photos, child = "PrevVisit_5A_Photopoints_wide.Rmd"}
```

```{r}
rm(list = ls())
```

