---
output: 
  pagedown::html_paged:
    css: www/styles_prevvisit.css
    toc: false
    numbered_sections: false
    number_sections: false
params:
  year: "2018"
  plot: "MABI-012"
---

#### Tree Measurements

```{r treem, include = F}
tree_p <- tree |> filter(Plot_Name %in% params$plot) 

tree_tab <- kable(tree_p |> select(Tag, ScientificName, Fork, Azimuth, Distance,
                                   Status, CrownClass, DBH, Decay, Note),
                  col.names = c("Tag", "Species", "Fork", "Az.", "Dist.", 
                                "Status", "Crown", "DBH", "Decay", "Note"),
                  table.attr = "class='table-striped'",
                  format = 'html', align = c('c', 'l', rep('c', 7), 'l')) |> 
            kable_styling(fixed_thead = TRUE, position = 'left', full_width = TRUE, 
                          font_size = 10) |> 
            column_spec(2, width = "1.2in")
                

```

```{r tree_tab}
tree_tab
```

```{r treemap, fig.width = 6, fig.height = 5.8, warning=FALSE,  message=FALSE}
suppressWarnings(
  plotTreeMap(park = params$park, from = as.numeric(params$year), 
            to = as.numeric(params$year), plotName = params$plot)
)
```