---
output: 
  pagedown::html_paged:
    css: www/styles_prevvisit.css
    toc: false
    numbered_sections: false
    number_sections: false
params:
  year: "2018"
  plot: "MABI-012"
  print: FALSE
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

library(pagedown)
library(tidyverse)
library(forestNETN)
library(htmltools)
library(knitr)
library(kableExtra)
library(ggrepel)
library(cowplot)
#devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0") # for collapse_rows()
library(kableExtra)
```

```{r import, include = FALSE, cache = FALSE}
forestNETN::importData()
```
```{r params, include = FALSE}
#params <- data.frame(year = 2022, plot = "MABI-021")

year <- as.numeric(params$year)
park <- substr(params$plot, 1, 4)
plot <- params$plot
```

```{r source, include = FALSE}
source("PrevVisit_FieldForms_NETN_compile.R")
```

```{r stand, child = "PrevVisit_1A_Stand_Data_long.Rmd"}
```

```{r visit_notes, child = "PrevVisit_1B_Visit_Notes.Rmd"}
```

```{r micro2A, child = "PrevVisit_2A_Microplot_Data.Rmd"}
```

```{r cwd, child = "PrevVisit_2B_CWD_Data.Rmd"}
```

### Previous Visit: Tree Data for `r paste0(params$plot, '-', params$year)` {.page-break-before} 

```{r tree3A, child = "PrevVisit_3A_Tree_Measurements.Rmd"}
```


```{r tree3B, child = "PrevVisit_3B_Tree_Conditions.Rmd"}
```

<br>

```{r tree3C, child = "PrevVisit_3C_Tree_Foliage_Cond.Rmd"}
```

### Previous Visit: Quadrat Data for `r paste0(params$plot, '-', params$year)` {.page-break-before} 

<hr>

```{r tree3C, child = "PrevVisit_4A_Quadrat_Data.Rmd"}
```


