---
output: 
  html_document:
    css: www/styles.css
    anchor_sections: FALSE
    includes:
        in_header: "header_manual.html"
params:
  year: 2019
  plot: "ACAD-047"
---
<div style="margin-left:-120px;width:100%">
QAQC Report for: <span style="font-weight:bold;">`r params$plot` `r params$year`</span> {.tabset .tabset-pills}
--------------------------------------------------
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')
```

```{r import, include = FALSE, cache = TRUE}
forestNETN::importData()
```

```{r deps, include = FALSE}
library(tidyverse)
library(forestNETN)
library(htmltools)
library(knitr)
library(kableExtra)

# Set up params (tends to work better)
year = as.numeric(params$year)
plot = params$plot

source("QAQC_functions.R")
```

```{r compile_data, include = FALSE}
source("Compile_QAQC_Data.R")
```

```{r stand_tables, include = FALSE}
site_char_tab <- kable(stand2 %>% select(Team, Stand_Structure, Txt_Crown_Closure, Water_on_Plot, 
                              Deer_Browse_Index, Microtopography, Earthworms), 
                       format = "html", align = 'c',
                       col.names = c("Team", "Stand Structure" ,"Crown Closure", "Water on Plot", 
                                     "Deer Browse Index", "Microtopography", "Earthworms")) %>% 
                 kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed', 
                               position = 'float_left') %>% 
                 row_spec(0, extra_css = 'border-bottom: 1px solid #000000;') %>% 
                 row_spec(1:2, extra_css = 'border-bottom: 1px solid #CACACA;') %>% 
                 column_spec(2, background = check_dif(stand2, "Stand_Structure")) %>% 
                 column_spec(3, background = check_dif(stand2, "Crown_Closure_code")) %>% 
                 column_spec(4, background = check_dif(stand2, "Water_on_Plot")) %>% 
                 column_spec(5, background = check_dif(stand2, "Deer_Browse_Index")) %>% 
                 column_spec(6, background = check_dif(stand2, "Microtopography")) %>% 
                 column_spec(7, background = check_dif(stand2, "Earthworms"))

pct_tab <- kable(stand2 %>% select(Team, Txt_Understory_Low, Txt_Understory_Mid, Txt_Understory_High,
                                   Txt_Bare_Soil, Txt_Rock, Txt_Trampled, Txt_Water,
                                   Txt_Bryophyte, Txt_Lichen),
                 format = 'html', align = 'c',
                 col.names = c("Team", "% Vasc. Low", "% Vasc. Mid", "% Vasc. High", 
                               "% Bare Soil", "% Rock", "% Trampled", "% Water",
                               "% Non-Vascular", "% Lichen")) %>% 
                 kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed', 
                               position = 'float_left') %>% 
                 row_spec(0, extra_css = 'border-bottom: 1px solid #000000;') %>% 
                 row_spec(1:2, extra_css = 'border-bottom: 1px solid #CACACA;') %>%
                 column_spec(2, background = check_dif(stand2, "Understory_Low_code")) %>% 
                 column_spec(3, background = check_dif(stand2, "Understory_Mid_code")) %>% 
                 column_spec(4, background = check_dif(stand2, "Understory_High_code")) %>% 
                 column_spec(5, background = check_dif(stand2, "Bare_Soil_code")) %>% 
                 column_spec(6, background = check_dif(stand2, "Rock_code")) %>% 
                 column_spec(7, background = check_dif(stand2, "Trampled_code")) %>% 
                 column_spec(8, background = check_dif(stand2, "Water_code")) %>% 
                 column_spec(9, background = check_dif(stand2, "Bryophyte_code")) %>% 
                 column_spec(10, background = check_dif(stand2, "Lichen_code")) 

trht_tab <- kable(tree_hts_wide %>% select(TagCode, CrownClassLabel, Crew, QAQC, ht_diff),
                  format = 'html', align = 'c',
                  table.attr = "style='width:48%;'",
                  col.names = c("Tree #", "Crown Class", "Crew", "QAQC", "Diff (m)")) %>% 
            kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed', full_width = FALSE, position = 'left') %>% 
                  row_spec(0, extra_css = 'border-bottom: 1px solid #000000;') %>% 
                  row_spec(1:(nrow(tree_hts_wide)-1), extra_css = 'border-bottom: 1px solid #CACACA;') %>%
                  column_spec(5, background = case_when(abs(tree_hts_wide$ht_diff) > 1 ~ diff_bad,
                                                        between(abs(tree_hts_wide$ht_diff), 0.1, 1) ~ diff_ok,
                                                        tree_hts_wide$ht_diff == 0 ~ '#ffffff')) %>% 
                  row_spec(nrow(tree_hts_wide), extra_css = "border-bottom: 1px solid #000000;")

dist_tab <- kable(dist %>% select(Team, DisturbanceSummary, ThresholdLabel, DisturbanceCoverClassLabel),
                  format = 'html', align = 'c',
                  table.attr = "style='width:48%;'",
                  col.names = c("Team", "Disturbance", "Threshold", "Cover Class")) %>% 
            kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed', full_width = FALSE, position = 'left') %>% 
                  row_spec(0, extra_css = 'border-bottom: 1px solid #000000;') %>% 
                  row_spec(1:2, extra_css = 'border-bottom: 1px solid #CACACA;') %>%
                  column_spec(2, background = check_dif(dist, "DisturbanceLabel")) %>% 
                  column_spec(3, background = check_dif(dist, "ThresholdLabel")) %>% 
                  column_spec(4, background = check_dif(dist, "DisturbanceCoverClassCode")) 

```

```{r tree_tables, include = FALSE}
tree_tab <- kable(tree_wide2 %>% select(-fol_diff, -dec_diff, -HWA_diff, -BBD_diff), 
                  format = 'html', align = 'c',
                  col.names = c("Tree", "Species", "DBH_C", "DBH_Q", "Diff", "Ver_C", "Ver_Q",
                                "Status_C", "Status_Q", "Crown_C", "Crown_Q", "TotFol_C", "TotFol_Q",
                                "Decay_C", "Decay_Q", "HWA_C", "HWA_Q", "BBD_C", "BBD_Q")) %>% 
            kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed', 
                          full_width = FALSE, position = 'left', font_size = 6) %>% 
            row_spec(0, extra_css = 'border-bottom: 1px solid #000000;') %>% 
            row_spec(1:nrow(tree_wide2), extra_css = 'border: 1px solid #CACACA;') %>% 
            column_spec(2, border_right = TRUE) %>% 
            column_spec(3:5, background = check_dbh(tree_wide2, "DBH_diff")) %>% 
            column_spec(5, border_right = TRUE) %>% 
            column_spec(6:7, background = 
                          ifelse(tree_wide2$IsDBHVerified_C != tree_wide2$IsDBHVerified_Q, diff_ok, "#ffffff")) %>% 
            column_spec(7, border_right = TRUE) %>% 
            column_spec(8:9, background = 
                          case_when(substr(tree_wide2$TreeStatusCode_C, 1, 1) != "R" &
                                    substr(tree_wide2$TreeStatusCode_C, 1, 1) != substr(tree_wide2$TreeStatusCode_Q, 1, 1) ~ diff_bad,
                                    substr(tree_wide2$TreeStatusCode_C, 1, 1) != "R" &
                                    tree_wide2$TreeStatusCode_C != tree_wide2$TreeStatusCode_Q ~ diff_ok,
                                    TRUE ~ "#ffffff")) %>% 
            column_spec(9, border_right = TRUE) %>% 
            column_spec(10:11, background = 
                          case_when(abs(tree_wide2$CrownClassCode_C - tree_wide2$CrownClassCode_Q) > 1 ~ diff_bad,
                                    abs(tree_wide2$CrownClassCode_C - tree_wide2$CrownClassCode_Q) == 1 ~ diff_ok,
                                    TRUE ~ "#ffffff")) %>% 
            column_spec(11, border_left = TRUE) %>% 
            column_spec(12:13, background = 
                          case_when(tree_wide$fol_diff > 1 ~ diff_bad,
                                    tree_wide$fol_diff == 1 ~ diff_ok,
                                    TRUE ~ "#ffffff")) %>% 
            column_spec(13, border_right = TRUE) %>% 
            column_spec(14:15, background = 
                          case_when(tree_wide2$dec_diff > 1 ~ diff_bad,
                                    tree_wide2$dec_diff == 1 ~ diff_ok,
                                    TRUE ~ "#ffffff")) %>% 
            column_spec(15, border_right = TRUE) %>% 
            column_spec(16:17, background = 
                          case_when(tree_wide2$HWA_diff > 1 ~ diff_bad,
                                    tree_wide2$HWA_diff == 1 ~ diff_ok,
                                    TRUE ~ "#ffffff")) %>% 
            column_spec(17, border_right = TRUE) %>% 
            column_spec(18:19, background = 
                          case_when(tree_wide2$BBD_diff > 1 ~ diff_bad,
                                    tree_wide2$BBD_diff == 1 ~ diff_ok,
                                    TRUE ~ "#ffffff"))  
   

  



```


### Stand {.tabset .tabset-pills}

<h3>Stand Characteristics</h3>
```{r, echo = FALSE}
site_char_tab
```
<br>

<h3>Stand % Cover Metrics</h3>
```{r, echo = FALSE}
pct_tab
```
<br>

<div class='column_1'>
<h3>Stand Height</h3>
```{r, echo = FALSE}
trht_tab
```
</div>

<div class='column_2'>
<h3>Disturbances</h3>
```{r, echo = FALSE}
dist_tab
```
</div>


### Tree {.tabset}

#### Tree Data {.tabset}
```{r, echo = FALSE}
tree_tab
```

#### Conditions

#### Foliage Conditions

### Microplot

### Quadrat Data

### Quadrat Species

### Add. Spp.

### CWD

### Soil

</div>
