---
output: 
  html_document:
    css: www/styles_prevvisit.css
    anchor_sections: FALSE
    toc: false
    numbered_sections: false
params: 
  print: FALSE
  park: "APCO"
  year: 2018
---

#### `r paste0(plot_name, " ", year)` 

```{r include = FALSE}


sap_p <- saps |> filter(Plot_Name %in% plot_name) |> 
  arrange(Plot_Name, Micro, Tag) |> mutate(PlotCode = substr(Plot_Name, 6, 8))

micro_rchange1 <- ifelse(lag(sap_p$Micro) == sap_p$Micro, NA_real_, 
                        as.numeric(paste0(row.names(sap_p)))) 

micro_rchange <- c(micro_rchange1[!is.na(micro_rchange1)])

sap_tab <- kable(sap_p |> select(PlotCode, Micro, Tag, Fork, ScientificName, DBHcm, Status, SaplingNote),
                  col.names = c("Plot", "Micro", "Tag", "Fork", "Species", "DBH", "Status", "Notes"),
                  format = 'html', align = c('c', 'c', 'c', 'c', 'l', 'c', 'c', 'l')) |> 
           kable_styling(fixed_thead = TRUE, position = 'left', full_width = TRUE, 
                         font_size = 11, bootstrap_options = c("bordered")) |>
           column_spec(1:3, width = "10%") |> 
           column_spec(c(5, 8), width = "25%") |> 
           column_spec(c(4, 6, 7), width = "5%") |>
           row_spec(c(micro_rchange), extra_css = 'border-bottom: 1.75px solid #000000') |> 
           row_spec(c(1, nrow(sap_p)), extra_css = 'border-bottom: 1.75px solid #000000')
           #collapse_rows(2, valign = 'middle', longtable_clean_cut = TRUE) 
```

```{r echo = F}
sap_tab
```

