---
output: 
  pagedown::html_paged:
    css: www/styles_prevvisit.css
    toc: false
    numbered_sections: false
    number_sections: false
params:
  print: TRUE
  plot_name: "APCO-176"
  year: 2022
  panel: 3
---
```{r include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

```

```{r echo = F, include = F, eval = F}
library(tidyverse)
library(kableExtra)
library(htmltools)
library(knitr)
library(forestNETN)
importData()

plot_name = params$plot_name
year = as.numeric(params$year)
park = substr(plot_name, 1, 4)
panel = params$panel
subunit <- joinLocEvent(park = substr(plot_name, 1, 4), from = year, to = year) |> 
  filter(Plot_Name == plot_name) |>  select(ParkSubUnit) |> as.character()

source("PrevVisit_FieldForms_NETN_compile.R")
#source("./PrevVisit_modules/PrevVisit_FieldForms_NETN_compile.R")
```

```{r echo = F, include = F, eval = F}
library(tidyverse)
library(htmltools)
library(kableExtra)
library(forestMIDN)
importData()

#params <- data.frame(plot_name = "APCO-176", year = 2022, panel = 3)
plot_name = params$plot_name
year = as.numeric(params$year)
park = substr(plot_name, 1, 4)
panel = params$panel
subunit <- joinLocEvent(park = substr(plot_name, 1, 4), from = year, to = year) |> 
  filter(Plot_Name == plot_name) |>  select(ParkSubUnit) |> as.character()

source("PrevVisit_FieldForms_MIDN_compile.R")
```

```{r, echo = F, include = F, eval = params$print}
plot_name = params$plot_name
year = as.numeric(params$year)
park = substr(plot_name, 1, 4)
subunit <- joinLocEvent(park = substr(plot_name, 1, 4), from = year, to = year) |> 
  filter(Plot_Name == plot_name) |>  select(ParkSubUnit) |> as.character()
```

```{r results = 'asis', echo = FALSE, eval = params$print}
cat("<h3> Previous Visit: Tree Data for ")

cat(paste0(plot_name, '-', year, "     ", substr(subunit, 6, nchar(subunit))), "</h3>")

cat("<hr>")
```


```{r include = F}
tree_p <- tree |> dplyr::filter(Plot_Name %in% plot_name) 

tree_tab <- kable(tree_p |> select(Tag, ScientificName, Fork, Azimuth, Distance,
                                   Status, CrownClass, DBH, Decay, Note),
                  col.names = c("Tag", "Species", "Fork", "Az.", "Dist.", 
                                "Status", "Crown", "DBH", "Decay", "Note"),
                  table.attr = "class='table-striped'",
                  format = 'html', align = c('c', 'l', rep('c', 7), 'l')) |> 
            kable_styling(fixed_thead = TRUE, position = 'left', full_width = TRUE, 
                          font_size = 10) |> 
            column_spec(2, width = "1.2in")
                

```

```{r echo = F}
tree_tab
```

