---
output: 
  pagedown::html_paged:
    css: www/styles_prevvisit.css
    toc: false
    numbered_sections: false
    number_sections: false
params:
  print: TRUE
  plot_name: "FRSP-001"
  year: 2019
---
```{r include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')
```

```{r, echo = F, include = F, eval = params$print}
plot_name = params$plot_name
year = as.numeric(params$year)
park = substr(plot_name, 1, 4)
subunit <- joinLocEvent(park = substr(plot_name, 1, 4), from = year, to = year) |> 
  filter(Plot_Name == plot_name) |>  select(ParkSubUnit) |> as.character()
```


```{r results = 'asis', echo = FALSE, eval = params$print}

cat("<h3> Previous Visit: Quadrat Data for ")
cat(paste0(plot_name, '-', year, "     ", substr(subunit, 6, nchar(subunit))), "</h3>")
cat("<hr>")
```

```{r include = F}
library(tidyverse)
library(kableExtra)
library(htmltools)
library(knitr)

quad_p <- quad_all |> filter(Plot_Name %in% plot_name) 

quad_tab <- kable(quad_p |> select(Species, A2, A5, A8, AA, B2, B5, B8, BB, C2, C5, C8, CC, Note),
                  #table.attr = "class='table-striped'", 
                  #table.attr = "class='quads'",
                  format = 'html', align = c('l', rep('c', 12))) |> 
            kable_styling(fixed_thead = TRUE, bootstrap_options = c('striped'),
                          position = 'left', full_width = TRUE, font_size = 9) |> 
            row_spec(0, extra_css = 'border-bottom: 2px solid #000000;') |> 
            row_spec(1, extra_css = 'border-bottom: 2px solid #000000;') |> 
            row_spec(8, extra_css = 'border-bottom: 2px solid #000000;') |> 
            column_spec(1, width = "120em") |> 
            column_spec(2:12, width = "50em") |> 
            column_spec(13, width = "70em")
```

<div class = 'quads'>
```{r }
quad_tab
```
</div>
<br>
<br>

<h4>Additional Species</h4>
```{r include = F}
addspp_p <- addspp |> filter(Plot_Name %in% plot_name) |> 
  select(Species = ScientificName) |> arrange(Species) |> c()

```

```{r results = 'asis'}
cat(noquote(addspp_p$Species), sep = ", ")
```

<hr>